---
pagetitle: "COVID-19 cases in GM"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse) ; library(lubridate) ; library(reactable) ; library(zoo) ; library(ggtext) ; library(scales) ; library(shiny)

# Mid-2018 population estimates
# Source: Nomis / ONS
# URL: https://www.nomisweb.co.uk/datasets/pestsyoala

population <- read_csv("http://www.nomisweb.co.uk/api/v01/dataset/NM_2002_1.data.csv?geography=1820327961...1820327970,1853882369,2092957699&date=latest&gender=0&c_age=200&measures=20100&select=date_name,geography_name,geography_code,gender_name,c_age_name,measures_name,obs_value,obs_status_name") %>% 
  select(area_code = GEOGRAPHY_CODE, population = OBS_VALUE)

# Confirmed cases
# Source: Public Health England
# URL: https://coronavirus.data.gov.uk

cases <- read_csv("https://coronavirus.data.gov.uk/downloads/csv/coronavirus-cases_latest.csv") %>% 
  filter(`Area type` %in% c("Nation", "Lower tier local authority"),
         `Area name` %in% c("Bolton", "Bury", "Manchester", "Oldham", "Rochdale", "Salford", "Stockport", "Tameside", "Trafford", "Wigan", "England")) %>% 
  mutate(date = as.Date(`Specimen date`, format = "%Y-%m-%d")) %>% 
  select(date,
         area_code = `Area code`,
         area_name = `Area name`,
         new_cases = `Daily lab-confirmed cases`) %>% 
  arrange(date) %>% 
  group_by(area_code, area_name) %>%
  complete(date = seq.Date(min(date), max(date), by = "day")) %>% 
  mutate(new_cases = replace_na(new_cases, 0)) %>% 
  ungroup() %>% 
  fill(area_name) %>%
  bind_rows(
    filter(., area_name != "England") %>% 
    group_by(., date) %>%
      summarise(area_code = "E47000001",
                area_name = "Greater Manchester",
                date = unique(date),
                new_cases = sum(new_cases))
    )
```

## Confirmed cases of coronavirus in Greater Manchester

```{r}
# confirmed cases within last 14 days
recent_cases <- cases %>% 
  filter(date >= max(date) - days(14)) %>% 
  group_by(area_code, area_name) %>% 
  summarise(date = max(date),
            recent_cases = sum(new_cases)) %>%
  ungroup() %>% 
  left_join(population, by = "area_code") %>% 
  mutate(area_name = fct_relevel(factor(area_name), "Bolton", "Bury", "Manchester", "Oldham", "Rochdale",  "Salford", "Stockport", "Tameside", "Trafford", "Wigan", "Greater Manchester", "England"),
         recent_rate = round(recent_cases/population*100000,1),
         recent_cases = as.integer(recent_cases),
         population = as.integer(population)) %>% 
  select(date, area_name, recent_cases, population, recent_rate) %>% 
  arrange(area_name) %>% 
  select(-date)

palette <- function(x) rgb(colorRamp(c("#e6eff3", "#39809e"))(x), maxColorValue = 255)

tbl <- reactable(recent_cases,
          class = "tbl",
          compact = TRUE,
          pagination = FALSE,
          wrap = FALSE,
          defaultColDef = colDef(headerClass = "header", align = "left"),
          columns = list(
            area_name = colDef(name = "Name"),
            recent_cases = colDef(name = "Total cases",
                                  format = colFormat(separators = TRUE),
                                  align = "left"),
            population = colDef(name = "Population",
                                format = colFormat(separators = TRUE),
                                align = "left"),
            recent_rate = colDef(name = "Rate per 100,000",
                                 align = "left",
                                 style = function(value) {
                                   normalized <- (value - min(recent_cases$recent_rate)) / (max(recent_cases$recent_rate) - min(recent_cases$recent_rate))
                                   color <- palette(normalized)
                                   list(background = color)
                                   }))
)
```

```{css}
@import url('https://fonts.googleapis.com/css2?family=Lato&display=swap');

.graphic-div {
  margin-left: 10% auto;
  font-family: 'Lato', sans-serif;
}

.title {
  font-size: 16px;
  font-weight: bold;
}

.subtitle {
  margin: 8px 0;
  font-size: 14px;
}

.tbl {
  font-size: 14px;
  line-height: 18px;
}

.tbl a {
  color: inherit;
}

.header {
  border-bottom: 2px solid #555;
  font-size: 14px;
  font-weight: bold;
}

.header:hover {
  background-color: #eee;
}

.caption {
  text-align: right;
  font-size: 12px;
  color: #212121;
}
```

<div class = "row">
<div class = "col-xs-12 col-sm-12 col-md-12 col-lg-6">
<div class = "graphic-div">
```{r fig.width=10, dev=c('svg')}
# rolling 14-day rate of cases
rolling_rate <- cases %>% 
  left_join(population, by = "area_code") %>% 
  mutate(rate = round(new_cases/population*100000,1), 
         ma_rate = rollmean(rate, 14, align = "right", fill = NA)) %>% 
  group_by(area_name) %>% 
  mutate(area_name = case_when(area_name == "Greater Manchester" ~ "GM",TRUE ~ area_name),
         label = str_c("<b style = 'color:#333333;font-size:14pt;'>", area_name, "</b><br/><span style = 'color:#757575;'>", comma(sum(new_cases)), "</span>"),
         cum_cases = sum(new_cases)) %>% 
  ungroup() %>% 
  mutate(label = fct_reorder(label, cum_cases, .desc = TRUE))

    div(class = "subtitle",
        div(class = "title", "New confirmed cases per 100,000 population"),
        paste("14-day moving average, up to", format(max(rolling_rate$date), '%d %B %Y')))
    
    ggplot(data = rolling_rate, aes(x = date, y = ma_rate, group = 1)) +
      geom_hline(yintercept = 0, size = 0.3, colour = "#333333") +
      geom_line(aes(colour = ifelse(date >= max(date)-14, "#39809E", "#bdbdbd")), 
                size = 1, show.legend = FALSE) +
      scale_color_identity() +
      scale_x_date(date_labels = "%b") +
      scale_y_continuous(expand = c(0.005, 0.005)) +
      labs(x = NULL, y = NULL, title = NULL, subtitle = NULL, caption = NULL) +
      theme_minimal(base_size = 14, base_family = "Lato") +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            strip.text.x = element_markdown(hjust = 0, lineheight = 1.2),
            axis.text = element_blank()) +
      facet_wrap(~label, nrow = 3)
    
    div(class = "caption", p("Source: ", a("Public Health England", href = 'https://coronavirus.data.gov.uk/', target = "_blank")))

```
</div>
</div>

<div class = "col-xs-12 col-sm-12 col-md-12 col-lg-6">
```{r table ui}
div(class = "graphic-div",
    div(class = "subtitle",
        div(class = "title", "New confirmed cases of coronavirus in the last 14 days"),
        paste("up to", format(max(cases$date), '%d %B %Y'))
        ),
    tbl,
    div(class = "caption", p("Source: ", a("Public Health England", href = 'https://coronavirus.data.gov.uk/', target = "_blank")))
    )
```
</div>
</div>